export enum RegiaoVegetal {
  SAO_PAULO_LITORAL_SUL = 'SAO_PAULO_LITORAL_SUL',
  SAO_PAULO_LITORAL_NORTE = 'SAO_PAULO_LITORAL_NORTE',
  SAO_PAULO_REGIAO_SUDESTE = 'SAO_PAULO_REGIAO_SUDESTE',
  SAO_PAULO_REGIAO_CENTRO = 'SAO_PAULO_REGIAO_CENTRO',
  SAO_PAULO_REGIAO_NOROESTE = 'SAO_PAULO_REGIAO_NOROESTE',
  SAO_PAULO_REGIAO_SUDOESTE = 'SAO_PAULO_REGIAO_SUDOESTE'
}
